apiVersion: v1
kind: Service
metadata:
  name: flight-price-predictor-service
spec:
  type: NodePort
  selector:
    app: flight-price-predictor
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007