services:
  sleek-airflow:
    build:
      context: ./airflow
      dockerfile: dockerfile
    container_name: sleek-airflow-container
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8081:8080"
    command: ["airflow", "standalone"]

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-container
    ports:
      - "8080:8080"
    volumes:
      - "D:/ALMABETTER PROJECTS/airflow-docker-demo/airflow:/opt/airflow"


volumes:
  jenkins_home:
